from typing import Dict, Any
from ..supabase_client import supabase, supabase_service


async def log_agent_execution(
    agent_name: str,
    action_type: str,
    input_payload: Dict[str, Any],
    output_payload: Dict[str, Any],
    reasoning: str
) -> bool:
    """
    Log an agent execution to the audit_logs table.
    
    Reusable helper for all optimization agents (Renewal Catcher, Cross Deal Negotiator, Strategic Agent).
    
    Args:
        agent_name: Name of the agent (e.g., "Renewal Catcher", "Cross Deal Negotiator")
        action_type: Type of action (e.g., "renewal_analysis", "crossdeal_analysis", "strategic_analysis")
        input_payload: Input data passed to the agent (stored as JSON)
        output_payload: Output data generated by the agent (stored as JSON)
        reasoning: Explanation of why this action was taken
    
    Returns:
        bool: True if logged successfully, False if logging failed
    
    Note:
        - Failures are logged to console but do not raise exceptions
        - Uses service role client if available, falls back to standard client
        - created_at is automatically set by Supabase
    """
    try:
        # Use service role client to bypass RLS if available
        client = supabase_service if supabase_service else supabase
        
        audit_record = {
            'agent_name': agent_name,
            'action_type': action_type,
            'input_payload': input_payload,
            'output_payload': output_payload,
            'reasoning': reasoning,
        }
        
        response = client.table('audit_logs').insert(audit_record).execute()
        
        if response.data:
            return True
        else:
            print(f"Audit logging returned no data for {agent_name} - {action_type}")
            return False
            
    except Exception as e:
        # Log error but don't raise - logging failures should not break the application
        print(f"Failed to log audit record for {agent_name}: {str(e)}")
        return False
